services:
    nickvergessen.newspage.controller:
        class: nickvergessen\newspage\controller\main
        arguments:
            - @config
            - @dispatcher
            - @template
            - @user
            - @controller.helper
            - @nickvergessen.newspage
            - %core.root_path%
            - %core.php_ext%

    nickvergessen.newspage.controller.settings:
        class: nickvergessen\newspage\controller\settings
        arguments:
            - @auth
            - @config
            - @request
            - @controller.helper
            - @user

    nickvergessen.newspage.helper:
        class: nickvergessen\newspage\helper
        arguments:
            - @controller.helper
            - @config

    nickvergessen.newspage:
        class: nickvergessen\newspage\newspage
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @content.visibility
            - @controller.helper
            - @nickvergessen.newspage.helper
            - @pagination
            - %core.root_path%
            - %core.php_ext%

    nickvergessen.newspage.menu_link_listener:
        class: nickvergessen\newspage\event\menu_link_listener
        arguments:
            - @nickvergessen.newspage.helper
            - @template
        tags:
            - { name: event.listener }

    nickvergessen.newspage.viewonline_listener:
        class: nickvergessen\newspage\event\viewonline_listener
        arguments:
            - @nickvergessen.newspage.helper
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
